# Four "servers" for the demo. In practice, these are machines in a data center or the cloud.
name: fleet

x-web: &web
  build: { context: ., dockerfile: web.Dockerfile }
  image: fleet-web
x-spam: &spam
  build: { context: ., dockerfile: spam.Dockerfile }
  image: fleet-spam

services:
  web1: { <<: *web, container_name: web1, ports: ["8081:80"] }
  web2: { <<: *web, container_name: web2, ports: ["8082:80"] }
  spam1: { <<: *spam, container_name: spam1 }
  spam2: { <<: *spam, container_name: spam2 }
